name: e2e

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      VITE_E2E: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Install Playwright browsers (best-effort)
        run: npx playwright install --with-deps || echo "skip"

      - name: Start dev server
        run: npm run dev:e2e & npx wait-on http://127.0.0.1:5173

      - name: Run e2e tests
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
